<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-11 10:00:22',
                'current_team_id' => NULL,
                'email' => 'prashantsingh2408@gmail.com',
                'email_verified_at' => NULL,
                'id' => 1,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant singh',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-11 10:00:22',
                'zip' => NULL,
            ),
            1 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-11 13:06:47',
                'current_team_id' => NULL,
                'email' => 'prashant24082@gmail.com',
                'email_verified_at' => NULL,
                'id' => 3,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant singh',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-11 13:06:47',
                'zip' => NULL,
            ),
            2 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-11 13:11:05',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24084@gmail.com',
                'email_verified_at' => NULL,
                'id' => 4,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant2 prashant',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-11 13:11:05',
                'zip' => NULL,
            ),
            3 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-11 15:41:34',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24082@gmail.com',
                'email_verified_at' => NULL,
                'id' => 5,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant2 prashant',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-11 15:41:34',
                'zip' => NULL,
            ),
            4 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-13 08:04:24',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24083@gmail.com',
                'email_verified_at' => NULL,
                'id' => 6,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant3 singh3',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-13 08:04:24',
                'zip' => NULL,
            ),
            5 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-13 08:19:28',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24085@gmail.com',
                'email_verified_at' => NULL,
                'id' => 7,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant5 singh5',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-13 08:19:28',
                'zip' => NULL,
            ),
            6 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-13 08:21:45',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24087@gmail.com',
                'email_verified_at' => NULL,
                'id' => 8,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant7 singh7',
                'password' => '83878c91171338902e0fe0fb97a8c47a',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-13 08:21:45',
                'zip' => NULL,
            ),
            7 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-13 08:27:12',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24088@gmail.com',
                'email_verified_at' => NULL,
                'id' => 9,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant8 singh8',
                'password' => '292bec9112e8d0eaf67d895f020f2dab',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-13 08:27:12',
                'zip' => NULL,
            ),
            8 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-13 11:15:33',
                'current_team_id' => NULL,
                'email' => 'prashantsingh24089@gmail.com',
                'email_verified_at' => NULL,
                'id' => 10,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'prashant9 singh9',
                'password' => '6445071763f7fa0b814c0317a19397da',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-13 11:15:33',
                'zip' => NULL,
            ),
            9 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2021-09-14 13:09:50',
                'current_team_id' => NULL,
                'email' => 'lokesh@pegalogics.com',
                'email_verified_at' => NULL,
                'id' => 11,
                'ip' => NULL,
                'mobile' => NULL,
                'name' => 'Lokesh Dewangan',
                'password' => '48e959d35feafde79e174747076efe8c',
                'pic' => NULL,
                'remember_token' => NULL,
                'state' => NULL,
                'status' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2021-09-14 13:09:50',
                'zip' => NULL,
            ),
        ));
        
        
    }
}